CREATE TYPE "SocialApprovalState" AS ENUM ('PENDING','APPROVED','REJECTED','CHANGES_REQUESTED','CANCELED');
CREATE TYPE "SocialApprovalDecisionKind" AS ENUM ('APPROVE','REJECT','REQUEST_CHANGES');
CREATE TABLE "SocialApprovalPolicy" ("id" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"name" TEXT NOT NULL,"version" INTEGER NOT NULL DEFAULT 1,"stages" JSONB NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "SocialApprovalPolicy_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SocialApprovalRequest" ("id" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"policyId" TEXT NOT NULL,"resourceType" TEXT NOT NULL,"resourceId" TEXT NOT NULL,"revisionId" TEXT NOT NULL,"submittedBy" TEXT NOT NULL,"state" "SocialApprovalState" NOT NULL DEFAULT 'PENDING',"currentStage" INTEGER NOT NULL DEFAULT 0,"idempotencyKey" TEXT NOT NULL,"payloadHash" TEXT NOT NULL,"correlationId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "SocialApprovalRequest_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SocialApprovalDecision" ("id" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"requestId" TEXT NOT NULL,"stage" INTEGER NOT NULL,"actor" TEXT NOT NULL,"decision" "SocialApprovalDecisionKind" NOT NULL,"comment" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "SocialApprovalDecision_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SocialExternalReviewToken" ("id" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"requestId" TEXT NOT NULL,"tokenHash" TEXT NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"maxUses" INTEGER NOT NULL DEFAULT 1,"uses" INTEGER NOT NULL DEFAULT 0,"revokedAt" TIMESTAMP(3),"createdBy" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "SocialExternalReviewToken_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "SocialApprovalPolicy_tenantId_name_version_key" ON "SocialApprovalPolicy"("tenantId","name","version");
CREATE INDEX "SocialApprovalPolicy_tenantId_active_idx" ON "SocialApprovalPolicy"("tenantId","active");
CREATE UNIQUE INDEX "SocialApprovalRequest_tenantId_idempotencyKey_key" ON "SocialApprovalRequest"("tenantId","idempotencyKey");
CREATE INDEX "SocialApprovalRequest_tenantId_state_createdAt_idx" ON "SocialApprovalRequest"("tenantId","state","createdAt");
CREATE UNIQUE INDEX "SocialApprovalDecision_requestId_stage_actor_key" ON "SocialApprovalDecision"("requestId","stage","actor");
CREATE INDEX "SocialApprovalDecision_tenantId_createdAt_idx" ON "SocialApprovalDecision"("tenantId","createdAt");
CREATE UNIQUE INDEX "SocialExternalReviewToken_tokenHash_key" ON "SocialExternalReviewToken"("tokenHash");
CREATE INDEX "SocialExternalReviewToken_tenantId_expiresAt_idx" ON "SocialExternalReviewToken"("tenantId","expiresAt");
ALTER TABLE "SocialApprovalPolicy" ADD CONSTRAINT "SocialApprovalPolicy_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SocialApprovalRequest" ADD CONSTRAINT "SocialApprovalRequest_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SocialApprovalRequest" ADD CONSTRAINT "SocialApprovalRequest_policyId_fkey" FOREIGN KEY ("policyId") REFERENCES "SocialApprovalPolicy"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SocialApprovalDecision" ADD CONSTRAINT "SocialApprovalDecision_requestId_fkey" FOREIGN KEY ("requestId") REFERENCES "SocialApprovalRequest"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SocialExternalReviewToken" ADD CONSTRAINT "SocialExternalReviewToken_requestId_fkey" FOREIGN KEY ("requestId") REFERENCES "SocialApprovalRequest"("id") ON DELETE CASCADE ON UPDATE CASCADE;
